# Generated by Django 4.2.5 on 2023-09-19 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areasaber',
            name='area',
        ),
    ]
