# Generated by Django 4.2.5 on 2023-09-19 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_areasaber_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocupacao',
            name='nome',
        ),
    ]
