# Generated by Django 4.2.5 on 2023-09-19 01:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_ocupacao_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='periodo',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='O periodo minimo é 1'), django.core.validators.MaxValueValidator(limit_value=10, message='O periodo maximo é 10')]),
        ),
    ]
