# Generated by Django 4.2.5 on 2023-09-19 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_periodo_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='periodo',
            field=models.PositiveIntegerField(),
        ),
    ]
