# Generated by Django 4.2.5 on 2023-09-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_periodo_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='periodo',
            field=models.CharField(max_length=255),
        ),
    ]
